apiVersion: v2
appVersion: "0.4.0"
name: aws-fsx-csi-driver
description: A Helm chart for AWS FSx for Lustre CSI Driver
version: 1.0.0
kubeVersion: ">=1.17.0-0"
home: https://github.com/kubernetes-sigs/aws-fsx-csi-driver
sources:
  - https://github.com/kubernetes-sigs/aws-fsx-csi-driver
keywords:
  - aws
  - fsx
  - csi
maintainers:
  - name: leakingtapan
